---
title: "Project 3 Final Report - Analysis Work"
author: "Madelynn Schina"
date: "April 2026"
output: pdf_document
---


```{r, include=F} 
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(here)
library(survival)
library(survminer)
library(car)
library(dplyr)
library(knitr)
library(kableExtra)
library(gtsummary)
library(gt)
library(gridExtra)
library(broom)

```


```{r, echo = F}
# Loading dataset
frmgham_data <- read.csv(here("Project 3/Data", "frmgham_data_cleaned.csv"))

# Separating data into male and female
male_data <- frmgham_data %>%
  filter(SEX == 1) %>%
  select(-SEX)

female_data <- frmgham_data %>%
  filter(SEX == 2) %>%
  select(-SEX)

```


```{r, echo = F, warning = FALSE}
# Exploratory Kaplan Meier Plots

# Calculate means
age_mean_f     <- mean(female_data$AGE, na.rm = TRUE)
totchol_mean_f <- mean(female_data$TOTCHOL, na.rm = TRUE)
bmi_mean_f     <- mean(female_data$BMI, na.rm = TRUE)

age_mean_m     <- mean(male_data$AGE, na.rm = TRUE)
totchol_mean_m <- mean(male_data$TOTCHOL, na.rm = TRUE)
bmi_mean_m     <- mean(male_data$BMI, na.rm = TRUE)

# Dichotomize using sex-specific means
female_data_clean <- female_data %>%
  mutate(AGE_cat = ifelse(AGE < age_mean_f, 
                          paste0("< ", round(age_mean_f, 1)), 
                          paste0("≥ ", round(age_mean_f, 1))),
         SYSBP_cat = ifelse(SYSBP < 160, "< 160", "≥ 160"),
         TOTCHOL_cat = ifelse(TOTCHOL < totchol_mean_f, 
                              paste0("< ", round(totchol_mean_f, 1)), 
                              paste0("≥ ", round(totchol_mean_f, 1))),
         BMI_cat = ifelse(BMI < bmi_mean_f, 
                          paste0("< ", round(bmi_mean_f, 1)), 
                          paste0("≥ ", round(bmi_mean_f, 1))))

male_data_clean <- male_data %>%
  mutate(AGE_cat = ifelse(AGE < age_mean_m, 
                          paste0("< ", round(age_mean_m, 1)), 
                          paste0("≥ ", round(age_mean_m, 1))),
         SYSBP_cat = ifelse(SYSBP < 160, "< 160", "≥ 160"),
         TOTCHOL_cat = ifelse(TOTCHOL < totchol_mean_m, 
                              paste0("< ", round(totchol_mean_m, 1)), 
                              paste0("≥ ", round(totchol_mean_m, 1))),
         BMI_cat = ifelse(BMI < bmi_mean_m, 
                          paste0("< ", round(bmi_mean_m, 1)), 
                          paste0("≥ ", round(bmi_mean_m, 1))))

# Creating function to make KM plots
km_plot <- function(data, var, label) {
  data$group <- data[[var]]
  fit <- survfit(Surv(stroke_time, stroke_10yr) ~ group, data = data)
  ggsurvplot(fit, data = data,
             conf.int = TRUE,
             ylim = c(0.90, 1),
             legend.title = label,
             legend.labs = levels(factor(data$group)),
             palette = c("cornflowerblue", "darkolivegreen2"),
             xlab = "Days",
             ylab = "Stroke-Free Survival",
             ggtheme = theme_minimal())$plot}


# Female Plots
plots_f <- list(km_plot(female_data_clean, "AGE_cat",     "Age"),
                km_plot(female_data_clean, "SYSBP_cat",   "SYSBP"),
                km_plot(female_data_clean, "DIABETES",    "Diabetes"),
                km_plot(female_data_clean, "BPMEDS",      "BP Meds"),
                km_plot(female_data_clean, "PREVCHD",     "Prev CHD"),
                km_plot(female_data_clean, "CURSMOKE",    "Smoking"),
                km_plot(female_data_clean, "TOTCHOL_cat", "Total Cholesterol"),
                km_plot(female_data_clean, "BMI_cat",     "BMI"))

# Male Plots
plots_m <- list(km_plot(male_data_clean, "AGE_cat",     "Age"),
                km_plot(male_data_clean, "SYSBP_cat",   "SYSBP"),
                km_plot(male_data_clean, "DIABETES",    "Diabetes"),
                km_plot(male_data_clean, "BPMEDS",      "BP Meds"),
                km_plot(male_data_clean, "PREVCHD",     "Prev CHD"),
                km_plot(male_data_clean, "CURSMOKE",    "Smoking"),
                km_plot(male_data_clean, "TOTCHOL_cat", "Total Cholesterol"),
                km_plot(male_data_clean, "BMI_cat",     "BMI"))


gridExtra::grid.arrange(grobs = plots_f, ncol = 4,
                        top = "Kaplan-Meier Curves by Covariate (Female)")
gridExtra::grid.arrange(grobs = plots_m, ncol = 4,
                        top = "Kaplan-Meier Curves by Covariate (Male)")

```




```{r, echo = F}
# Checking multicollinearity of predictors before performing variable selection
# Female
cox_vif_f <- coxph(Surv(stroke_time, stroke_10yr) ~ 
                     SYSBP + BPMEDS + DIABETES + AGE + PREVCHD + CURSMOKE + TOTCHOL + BMI,
                   data = female_data)
vif(cox_vif_f)

# Male
cox_vif_m <- coxph(Surv(stroke_time, stroke_10yr) ~ 
                     SYSBP + BPMEDS + DIABETES + AGE + PREVCHD + CURSMOKE + TOTCHOL + BMI,
                   data = male_data)
vif(cox_vif_m)

# Everything looks good, no concerns

```



```{r, echo = F}
# Variable Selection of additional covariates
# Required Covariates: AGE, SYSBP, DIABETES
# To Be Considered: BPMEDS, PREVCHD, CURSMOKE, TOTCHOL, BMI


# Variables of interest
vars <- c("stroke_time", "stroke_10yr", "AGE", "SYSBP", "DIABETES", "BPMEDS", "PREVCHD", 
          "CURSMOKE", "TOTCHOL", "BMI")

# Creating clean complete-cases subsets
female_data_clean <- female_data[complete.cases(female_data[, vars]), ]
male_data_clean <- male_data[complete.cases(male_data[, vars]), ]


## Females
# Full model
cox_full_f <- coxph(Surv(stroke_time, stroke_10yr) ~ AGE + SYSBP + DIABETES + BPMEDS + PREVCHD + CURSMOKE + TOTCHOL + BMI,
                    data = female_data_clean)

# Backward selection by AIC
cox_step_f <- step(cox_full_f, 
                   direction = "backward",
                   scope = list(lower = ~ AGE + SYSBP + DIABETES,
                                upper = ~ AGE + SYSBP + DIABETES + BPMEDS + PREVCHD + CURSMOKE + TOTCHOL + BMI))
summary(cox_step_f)


## Males
# Full model
cox_full_m <- coxph(Surv(stroke_time, stroke_10yr) ~ AGE + SYSBP + DIABETES + BPMEDS + PREVCHD + CURSMOKE + TOTCHOL + BMI,
                    data = male_data_clean)

# Backward selection by AIC
cox_step_m <- step(cox_full_m, 
                   direction = "backward",
                   scope = list(lower = ~ AGE + SYSBP + DIABETES,
                                upper = ~ AGE + SYSBP + DIABETES + BPMEDS + PREVCHD + CURSMOKE + TOTCHOL + BMI))
summary(cox_step_m)


# By backwards selection using AIC, the female model will include none of the five suggested covariates and the male model will include smoking status

```




```{r, echo = F}
# Now that we have completed variable selection, we will redo complete case analysis to maximize the number of patients included
# Female final model variables: AGE, SYSBP, DIABETES
vars_f <- c("stroke_time", "stroke_10yr", "AGE", "SYSBP", "DIABETES", "CURSMOKE")
female_data_cleaned <- female_data[complete.cases(female_data[, vars_f]), ]

# Male final model variables: AGE, SYSBP, DIABETES, CURSMOKE
vars_m <- c("stroke_time", "stroke_10yr", "AGE", "SYSBP", "DIABETES", "CURSMOKE")
male_data_cleaned <- male_data[complete.cases(male_data[, vars_m]), ]


# Fitting Cox PH Models
cox_final_f <- coxph(Surv(stroke_time, stroke_10yr) ~ AGE + SYSBP + DIABETES + CURSMOKE,
                     data = female_data_cleaned)
summary(cox_final_f)

cox_final_m <- coxph(Surv(stroke_time, stroke_10yr) ~ AGE + SYSBP + DIABETES + CURSMOKE,
                     data = male_data_cleaned)
summary(cox_final_m)


# Creating table to summarize model results
f_tidy <- tidy(cox_final_f, exponentiate = TRUE, conf.int = TRUE)
m_tidy <- tidy(cox_final_m, exponentiate = TRUE, conf.int = TRUE)

format_p <- function(p) {ifelse(p < 0.001, "<0.001", round(p, 3))}


model_table <- data.frame(Predictor = c("Age", "Systolic Blood Pressure", "Diabetes", "Current Smoker"),
                          HR_f = round(f_tidy$estimate, 3),
                          CI_f = paste0("(", round(f_tidy$conf.low, 3), ", ", round(f_tidy$conf.high, 3), ")"),
                          P_f  = format_p(f_tidy$p.value),
                          HR_m = round(m_tidy$estimate, 3),
                          CI_m = paste0("(", round(m_tidy$conf.low, 3), ", ", round(m_tidy$conf.high, 3), ")"),
                          P_m  = format_p(m_tidy$p.value))

kable(model_table,
      format = "html",
      col.names = c("Predictor", "HR", "95% CI", "p-value", "HR", "95% CI", "p-value"),
      caption = "Cox Proportional Hazards Model Results") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = FALSE) %>%
  add_header_above(c(" " = 1,
                     "Female" = 3,
                     "Male" = 3))

```

```{r, echo = F}
# Figures to check proportional hazards assumptions
ph_test_f <- cox.zph(cox_final_f)
ggcoxzph(ph_test_f)

ph_test_m <- cox.zph(cox_final_m)
ggcoxzph(ph_test_m)

```




```{r, echo = F}
# Risk Profile Assessments
# Defining profiles
# Profile order: Healthy, High BP, Diabetes, High BP + Diabetes, Smoker
profiles <- data.frame(AGE = rep(c(40, 50, 60), 5),
                       SYSBP = rep(c(110, 160, 110, 160, 110), each = 3),
                       DIABETES = rep(c(0, 0, 1, 1, 0), each = 3),
                       CURSMOKE = rep(c(0, 0, 0, 0, 1), each = 3))

#### Female Profiles ####
# Fitting model to profiles of interest
surv_f <- survfit(cox_final_f, newdata = profiles)

# Getting 10-year survival probabilities for each profile
surv_f_10yr <- as.vector(summary(surv_f, times = 3652.5)$surv)

# Formatting results
risk_table_f <- data.frame(Age = c(40, 50, 60),
                           Healthy = round(surv_f_10yr[1:3], 3),
                           HighBP = round(surv_f_10yr[4:6], 3),
                           Diabetes = round(surv_f_10yr[7:9], 3),
                           BP_Diab = round(surv_f_10yr[10:12], 3),
                           Smoker = round(surv_f_10yr[13:15], 3))


#### Male Profiles ####
# Fitting model to profiles of interest
surv_m <- survfit(cox_final_m, newdata = profiles)

# Getting 10-year survival probabilities for each profile
surv_m_10yr <- as.vector(summary(surv_m, times = 3652.5)$surv)

# Formatting results
risk_table_m <- data.frame(Age = c(40, 50, 60),
                           Healthy  = round(surv_m_10yr[1:3], 3),
                           HighBP = round(surv_m_10yr[4:6], 3),
                           Diabetes = round(surv_m_10yr[7:9], 3),
                           BP_Diab = round(surv_m_10yr[10:12], 3),
                           Smoker = round(surv_m_10yr[13:15], 3))

# Combine male and female tables
risk_table_combined <- rbind(risk_table_f, risk_table_m)

# Combined table with pack_rows for sex subheaders
kable(risk_table_combined,
      col.names = c("Age", "Healthy", "High BP", 
                    "Diabetes", "High BP + Diabetes", "Smoker"),
      caption = "10-Year Stroke-Free Survival Probabilities by Risk Profile") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = FALSE) %>%
  pack_rows("Female", 1, 3) %>%
  pack_rows("Male", 4, 6)

```






```{r, echo = F}
# Creating table 1 for report
summary_data <- frmgham_data %>%
  select(SEX, stroke_10yr, DIABETES, SYSBP, AGE, PREVCHD, BPMEDS, CURSMOKE, TOTCHOL, BMI)

# Renaming ADH, RACE, EDUCBAS, and SMOKE for table
summary_data <- summary_data %>%
  mutate(SEX = factor(SEX,
                      levels = c(1,2),
                      labels = c("Males", "Females")),
         DIABETES = factor(DIABETES,
                           levels = c(0,1),
                           labels = c("No", "Yes")),
         PREVCHD = factor(PREVCHD,
                          levels = c(0,1),
                          labels = c("Free of Disease",
                                     "Prevalent Disease")),
         BPMEDS = factor(BPMEDS,
                         levels = c(0,1),
                         labels = c("Not Currently Taken",
                                    "Currently Taken")),
         CURSMOKE = factor(CURSMOKE,
                           levels = c(0,1),
                           labels = c("Not Current Smoker",
                                      "Current Smoker")),
         stroke_10yr = factor(stroke_10yr,
                              levels = c(0,1),
                              labels = c("No", "Yes")))


# Creating summary table
descriptive_table <- tbl_summary(summary_data,
                                 by = SEX,
                                 missing = "ifany",
                                 type = list(DIABETES ~ "categorical"),
                                 statistic = list(all_continuous() ~ "{mean} ({sd})",
                                                  all_categorical() ~ "{n} ({p}%)"),
                                 label = list(stroke_10yr ~ "Stroke within 10 Years",
                                              DIABETES ~ "Diabetes",
                                              SYSBP ~ "Systolic Blood Pressure (mmHg)",
                                              AGE ~ "Age (years)",
                                              PREVCHD ~ "Coronary Heart Disease",
                                              BPMEDS ~ "Taking Blood Pressure Medication",
                                              TOTCHOL ~ "Total Cholesterol (mg/dL)",
                                              CURSMOKE ~ "Smoking Status",
                                              BMI ~ "BMI (kg/m^2)")) %>%
  add_overall() %>%
  modify_table_body(~ .x %>%
                      dplyr::mutate(label = ifelse(label == "Unknown", "Missing", label)))

# Save table as image for report
gtsave(as_gt(descriptive_table), "descriptivetable_finalreport.png")

```









```{r, echo = F}
# Secondary Analysis
# Loading original dataset that is not subset to only look at 10 years
frmgham_data_sa <- read.csv(here("Project 3/Data", "frmgham2.csv"))

```

```{r, echo = F}
# Summarize SYSBP and DIABETES by sex and period
summary_table <- frmgham_data_sa %>%
  group_by(SEX, PERIOD) %>%
  summarise(SYSBP_mean = round(mean(SYSBP, na.rm = TRUE), 1),
            SYSBP_sd   = round(sd(SYSBP, na.rm = TRUE), 1),
            Diabetes_pct = round(mean(DIABETES, na.rm = TRUE) * 100, 1),
            .groups = "drop") %>%
  mutate(SYSBP_fmt    = paste0(SYSBP_mean, " (", SYSBP_sd, ")"),
         Diabetes_fmt = paste0(Diabetes_pct, "%"))

# Reshape to wide format (one column per period)
table_wide <- data.frame(
  Variable = rep(c("SYSBP", "Diabetes"), 2),
  Sex = rep(c("Female", "Male"), each = 2),
  Period1 = c(summary_table$SYSBP_fmt[summary_table$SEX == 1 & summary_table$PERIOD == 1],
              summary_table$Diabetes_fmt[summary_table$SEX == 1 & summary_table$PERIOD == 1],
              summary_table$SYSBP_fmt[summary_table$SEX == 2 & summary_table$PERIOD == 1],
              summary_table$Diabetes_fmt[summary_table$SEX == 2 & summary_table$PERIOD == 1]),
  Period2 = c(summary_table$SYSBP_fmt[summary_table$SEX == 1 & summary_table$PERIOD == 2],
              summary_table$Diabetes_fmt[summary_table$SEX == 1 & summary_table$PERIOD == 2],
              summary_table$SYSBP_fmt[summary_table$SEX == 2 & summary_table$PERIOD == 2],
              summary_table$Diabetes_fmt[summary_table$SEX == 2 & summary_table$PERIOD == 2]),
  Period3 = c(summary_table$SYSBP_fmt[summary_table$SEX == 1 & summary_table$PERIOD == 3],
              summary_table$Diabetes_fmt[summary_table$SEX == 1 & summary_table$PERIOD == 3],
              summary_table$SYSBP_fmt[summary_table$SEX == 2 & summary_table$PERIOD == 3],
              summary_table$Diabetes_fmt[summary_table$SEX == 2 & summary_table$PERIOD == 3]))

# Build kable
kable(table_wide[, c("Variable", "Period1", "Period2", "Period3")],
      col.names = c("", "Period 1", "Period 2", "Period 3"),
      caption = "SYSBP and Diabetes Status Across Time Periods by Sex") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = FALSE) %>%
  pack_rows("Female", 1, 2) %>%
  pack_rows("Male", 3, 4) %>%
  column_spec(1:4, width = "2.5cm")

```

```{r, echo = F}
# Getting proportion of patients with clinically meaningful changes in BP or diabetes over the three time periods
individual_changes <- frmgham_data_sa %>%
  group_by(RANDID) %>%
  summarise(SYSBP_min    = min(SYSBP, na.rm = TRUE),
            SYSBP_max    = max(SYSBP, na.rm = TRUE),
            DIAB_min     = min(DIABETES, na.rm = TRUE),
            DIAB_max     = max(DIABETES, na.rm = TRUE)) %>%
  mutate(SYSBP_change = SYSBP_max - SYSBP_min,
         meaningful_SYSBP  = SYSBP_change >= 10,
         meaningful_DIAB   = DIAB_max != DIAB_min
  )

# Proportion with meaningful changes
mean(individual_changes$meaningful_SYSBP, na.rm = TRUE) * 100
mean(individual_changes$meaningful_DIAB, na.rm = TRUE) * 100

```



